#!/usr/bin/env nextflow

/*
 * Pipeline parameters
 */

// file of input files, one per line
params.input_csv = "${projectDir}/data/paired-end.csv"
// folder with the genome index generated by STAR
params.genome_index="${projectDir}/data/genome/genome_index"

// simple genome indices for GATK (and Picard)
params.genome="${projectDir}/data/genome/genome.fa"
params.genome_fai="${projectDir}/data/genome/genome.fa.fai"
params.genome_dict="${projectDir}/data/genome/genome.dict"

// Standard SNPs and indels for GATK
params.snpdb="${projectDir}/data/snp_db/snpdb.vcf.gz"
params.snpdb_index="${projectDir}/data/snp_db/snpdb.vcf.gz.tbi"
params.indels="${projectDir}/data/snp_db/indels.vcf.gz"
params.indels_ndex="${projectDir}/data/snp_db/indels.vcf.gz.tbi"

include { FASTP } from './modules/fastp/main.nf'
include { STAR } from './modules/star/main.nf'
include { GATK_ADD_REPLACE_READ_GROUPS } from './modules/gatk/readgroups/main.nf'
include { GATK_MARK_DUPLICATES } from './modules/gatk/markduplicates/main.nf'
include { GATK_SPLIT_NCIGAR_READS } from './modules/gatk/splitncigar/main.nf'
include { GATK_BASE_RECALIBRATOR } from './modules/gatk/baserecalibrate/main.nf'
include { GATK_APPLY_BQSR } from './modules/gatk/applybqsr/main.nf'
include { GATK_HAPLOTYPE_CALLER } from './modules/gatk/haplotypecaller/main.nf'


workflow {

    read_ch = Channel.fromPath(params.input_csv)
        .splitCsv(header:true)
        .map { row -> [row.sample_id, file(row.fastq_1), file(row.fastq_2)] }

    FASTP(read_ch)

    STAR(FASTP.out.trimmed_reads, params.genome_index)

    GATK_ADD_REPLACE_READ_GROUPS(STAR.out.bam)

    GATK_MARK_DUPLICATES(GATK_ADD_REPLACE_READ_GROUPS.out.rgs)

    GATK_SPLIT_NCIGAR_READS(GATK_MARK_DUPLICATES.out.dups, params.genome, params.genome_fai, 
        params.genome_dict)

    GATK_BASE_RECALIBRATOR(GATK_SPLIT_NCIGAR_READS.out.cigar, params.genome, 
        params.genome_fai, params.genome_dict, params.snpdb, params.snpdb_index, params.indels,
        params.indels_ndex)
    
    GATK_APPLY_BQSR(GATK_BASE_RECALIBRATOR.out.baserecal, params.genome, 
        params.genome_fai, params.genome_dict)

    GATK_HAPLOTYPE_CALLER(GATK_APPLY_BQSR.out.bqsrapplied, params.genome, 
        params.genome_fai, params.genome_dict, params.snpdb, params.snpdb_index)
}
